import Camera       from './form-elements/camera.jsx';
import Checkboxes   from './form-elements/checkboxes.jsx';
import DatePicker   from './form-elements/date-picker.jsx';
import Download     from './form-elements/download.jsx';
import Dropdown     from './form-elements/dropdown.jsx';
import Email        from './form-elements/email.jsx';
import FirstName    from './form-elements/first-name.jsx';
import Header       from './form-elements/header.jsx';
import HyperLink    from './form-elements/hyperlink.jsx';
import LineBreak    from './form-elements/line-break.jsx';
import Paragraph    from './form-elements/paragraph.jsx';
import RadioButtons from './form-elements/radio-buttons.jsx';
import Range        from './form-elements/range.jsx';
import Rating       from './form-elements/rating.jsx';
import Signature    from './form-elements/signature.jsx';
import Tags         from './form-elements/tags.jsx';
import Telephone    from './form-elements/telephone.jsx';
import TextArea     from './form-elements/text-area.jsx';
import TextInput    from './form-elements/text-input.jsx';
import TrueFalse    from './form-elements/true-false.jsx';

let FormElements = {};

FormElements.Camera = Camera;
FormElements.Checkboxes = Checkboxes;
FormElements.DatePicker = DatePicker;
FormElements.Download = Download;
FormElements.Dropdown = Dropdown;
FormElements.Email = Email;
FormElements.FirstName = FirstName;
FormElements.Header = Header;
FormElements.HyperLink = HyperLink;
FormElements.LineBreak = LineBreak;
FormElements.Paragraph = Paragraph;
FormElements.RadioButtons = RadioButtons;
FormElements.Range = Range;
FormElements.Rating = Rating;
FormElements.Signature = Signature;
FormElements.Tags = Tags;
FormElements.Telephone = Telephone;
FormElements.TextArea = TextArea;
FormElements.TextInput = TextInput;
FormElements.TrueFalse = TrueFalse;

module.exports = FormElements;
